#!/bin/bash

set -e

kube_version="v1.4.4"
helm_version="v2.0.0-beta.2"
minikube_version="v0.12.0"

pre_install () {
  wget "$1" -O "$HOME/$2"
  tar zxvf "$HOME/$2" -C $HOME/
}

post_install () {
  chmod +x "$HOME/$1"
  cp "$HOME/$1" /usr/local/bin/
}

command_exists () {
  type "$1" &> /dev/null ;
}

echo 'Make a sandwich, this may take a few'

if ! command_exists docker; then
  echo 'installing docker...'
  brew install docker
  brew install docker-machine
fi

if ! command_exists kubectl; then
  echo 'installing kubectl...'
  pre_install https://github.com/kubernetes/kubernetes/releases/download/${kube_version}/kubernetes.tar.gz kubernetes.tar.gz 
  post_install kubernetes/platforms/darwin/amd64/kubectl
fi

if ! command_exists helm; then
  echo 'installing helm...'
  pre_install http://storage.googleapis.com/kubernetes-helm/helm-${helm_version}-darwin-amd64.tar.gz helm-${helm_version}-darwin-amd64.tar.gz
  post_install darwin-amd64/helm
  if [[ ! -d $HOME/.helm ]]; then
    mkdir $HOME/.helm
    echo "Created helm home at ~/.helm..."
  fi
fi

if ! command_exists minikube; then
  echo 'installing minikube...'
  wget https://storage.googleapis.com/minikube/releases/${minikube_version}/minikube-darwin-amd64 -O minikube
  chmod +x minikube
  mv minikube /usr/local/bin/minikube
fi
